### ISSUE TITLE
Fix documentation error about fetching query results in joern server mode

### ISSUE THREAD

**Issue by NdibeRaymond** [joernio/website#40]
In the server page of joern documentation, developers are told they can fetch query results with the endpoint "result?uuid=$uuid", see image below:
![joern_doc_error](https://user-images.githubusercontent.com/40905613/121241197-16036100-c893-11eb-8fbb-11b565b43cdc.PNG)

However this is wrong and misleading as using the endpoint "result?uuid=$uuid" to fetch query results will fail.

**Comment by tuxology** [comment]
Yeah, I think its just `result/$uuid`. Ref: https://github.com/joernio/cpgqls-client-js/blob/master/client.js#L46 Mind sending a quick PR?
